# Generated by Django 5.2.1 on 2025-05-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['full_name'], 'verbose_name': 'Formateur', 'verbose_name_plural': 'Formateurs'},
        ),
    ]
